//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameWorke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cf_FactoryHouseDetials
    {
        public int Id { get; set; }
        public int FactoryHouseId { get; set; }
        public string FactoryHouseContent { get; set; }
        public string TailContent { get; set; }
        public string QuYu { get; set; }
        public string DiZhi { get; set; }
        public string ChangFangLeiXing { get; set; }
        public string LianXiRen { get; set; }
        public string LianXiRenShenFen { get; set; }
        public string LianXiRenShouJi { get; set; }
        public string ChangFangLeiBie { get; set; }
        public string JianZhuJieGou { get; set; }
        public string KuaDu { get; set; }
        public string DuYuan { get; set; }
        public string ZhanDiMianJi { get; set; }
        public string ChangFangMianJi { get; set; }
        public string BanGongMianJi { get; set; }
        public string SuSheMianJi { get; set; }
        public string KongDiMianJi { get; set; }
        public string CengGao { get; set; }
        public string XianPeiDian { get; set; }
        public string KePeiDian { get; set; }
        public string XinJiuChengDu { get; set; }
        public string ChanQuan { get; set; }
        public string XingChe { get; set; }
        public string DianTi { get; set; }
        public string ShiHeHangYe { get; set; }
        public string ChangFangTeSe { get; set; }
        public string XiaoFang { get; set; }
        public string ShiJian { get; set; }
        public string LianXiRenQq { get; set; }
        public Nullable<System.DateTime> F_CreateDate { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_ModifyUserId { get; set; }
        public string F_ModifyUserName { get; set; }
    }
}
