//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameWorke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jw_UserVisitLog
    {
        public string Id { get; set; }
        public string UserHostAddress { get; set; }
        public string UserHostName { get; set; }
        public string UrlAbsoluteUri { get; set; }
        public string PhysicalPath { get; set; }
        public string UserAgent { get; set; }
        public string HttpMethod { get; set; }
        public string UserLanguages { get; set; }
        public string UrlHost { get; set; }
        public string UrlPort { get; set; }
        public Nullable<int> TotalBytes { get; set; }
        public Nullable<int> ContentLength { get; set; }
        public string IsLocal { get; set; }
        public string BrowserType { get; set; }
        public string BrowserVersion { get; set; }
        public string BrowserPlatform { get; set; }
        public string BrowserBeta { get; set; }
        public string BrowserActiveXControls { get; set; }
        public string BrowserCookies { get; set; }
        public string BrowserCrawler { get; set; }
        public string BrowserJavaScript { get; set; }
        public string BrowserSupportsXmlHttp { get; set; }
        public string BrowserInputType { get; set; }
        public Nullable<int> BrowserScreenPixelsWidth { get; set; }
        public Nullable<int> BrowserScreenPixelsHeight { get; set; }
        public string UrlReferrerAbsoluteUri { get; set; }
        public string UrlReferrerAbsoluteUriDecode { get; set; }
        public string UrlReferrerHostName { get; set; }
        public string CanCombineFormsInDeck { get; set; }
        public string IsMobileDevice { get; set; }
        public string MobileDeviceManufacturer { get; set; }
        public string MobileDeviceModel { get; set; }
        public Nullable<int> NumberOfSoftkeys { get; set; }
        public string ContentEncoding { get; set; }
        public Nullable<int> ScreenBitDepth { get; set; }
        public string Website { get; set; }
        public string WebCookies { get; set; }
        public Nullable<System.DateTime> VisitTime { get; set; }
        public Nullable<int> AnalysisState { get; set; }
    }
}
