//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameWorke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jw_UserVisitLog
    {
        public string Id { get; set; }
        public string Ip { get; set; }
        public Nullable<bool> HasFormContentType { get; set; }
        public string Host { get; set; }
        public string Method { get; set; }
        public string Path { get; set; }
        public string Protocol { get; set; }
        public string Scheme { get; set; }
        public string QueryString { get; set; }
        public string Accept { get; set; }
        public byte[] AcceptEncoding { get; set; }
        public byte[] AcceptLanguage { get; set; }
        public string Connection { get; set; }
        public byte[] Cookie { get; set; }
        public byte[] UserAgent { get; set; }
        public string UpgradeInsecureRequests { get; set; }
        public Nullable<System.DateTime> ExcuteEndTime { get; set; }
        public Nullable<System.DateTime> ExcuteStartTime { get; set; }
        public string RequestBody { get; set; }
        public string ResponseBody { get; set; }
    }
}
