//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameWorke
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataCenterEntities : DbContext
    {
        public DataCenterEntities()
            : base("name=DataCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jw_UserVisitLog> Jw_UserVisitLog { get; set; }
        public virtual DbSet<Cf_Area> Cf_Area { get; set; }
        public virtual DbSet<Cf_CitySiteRangeSearch> Cf_CitySiteRangeSearch { get; set; }
        public virtual DbSet<Cf_ConditionalGroup> Cf_ConditionalGroup { get; set; }
    }
}
