//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jw_AzGame
    {
        public int Id { get; set; }
        public bool IsEnable { get; set; }
        public string Code { get; set; }
        public string QRCode { get; set; }        
        public string Name { get; set; }
        public string Edition { get; set; }
        public int? DownloadsNumber { get; set; }        
        public string CoverMap { get; set; }
        public string AzGameClassName { get; set; }
        public int AzGameClassId { get; set; }
        public int Size { get; set; }
        public string GameSize { get; set; }
        public string LanguageName { get; set; }
        public int Sort { get; set; }
        public Nullable<System.DateTime> OnlineTime { get; set; }
        public string DownloadAddress { get; set; }
        public int Praise { get; set; }
        public int BadEvaluation { get; set; }
        public string SeoTile { get; set; }
        public string SeoKey { get; set; }
        public string SeoDesc { get; set; }
        public DateTime F_CreateDate { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_ModifyUserId { get; set; }
        public string F_ModifyUserName { get; set; }
    }
}
